# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=
endif
export config

PROJECTS := cppzoo

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

cppzoo: 
	@echo "==== Building cppzoo ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f cppzoo.make

clean:
	@${MAKE} --no-print-directory -C . -f cppzoo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   "
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cppzoo"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
